site_name: CIS Controls Self Assessment Tool Document Library

nav:
    - Home: index.md
    - GENERAL:
        - 'About the CIS Controls': source/About the CIS Controls.md
        - 'About the CIS Controls Assessment Specification': source/About the CIS Controls Assessment Specification.md
        - 'Terms of Use': source/terms-of-use.md
        - 'Contributing': source/contributing.rst.md
    - CIS CONTROLS:
        - 'CIS Control 1: Inventory and Control of Enterprise Assets': source/Controls1.md
        - 'CIS Control 2: Inventory and Control of Software Assets': source/Controls2.md
        - 'CIS Control 3: Data Protection': source/Controls3.md
        - 'CIS Control 4: Secure Configuration of Enterprise Assets and Software': source/Controls4.md
        - 'CIS Control 5: Account Management': source/Controls5.md
        - 'CIS Control 6: Access Control Management': source/Controls6.md
        - 'CIS Control 7: Continuous Vulnerability Management': source/Controls7.md
        - 'CIS Control 8: Audit Log Management': source/Controls8.md
        - 'CIS Control 9: Email and Web Browser Protections': source/Controls9.md
        - 'CIS Control 10: Malware Defenses': source/Controls10.md
        - 'CIS Control 11: Data Recovery': source/Controls11.md
        - 'CIS Control 12: Network Infrastructure Management': source/Controls12.md
        - 'CIS Control 13: Network Monitoring and Defense': source/Controls13.md
        - 'CIS Control 14: Security Awareness and Skills Training': source/Controls14.md
        
theme:
    name: readthedocs
